export const productos = [
  {
    id: 1,
    title: "Remera térmica",
    price: 4500,
    stock: 10,
    description: "Remera térmica ideal para entrenar en el invierno",
    category: "remeras",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357577/remeraTermica_fcnzik.jpg",
  },
  {
    id: 2,
    title: "Buzo Mars",
    price: 7500,
    stock: 3,
    description: "Buzo con capucha canchero para estar en onda y abrigado",
    category: "buzos",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357574/buzoMarz_lwz6ob.jpg",
  },
  {
    id: 3,
    title: "Buzo Drew",
    price: 7500,
    stock: 4,
    description: "Buzo con capucha y bolsillo canguro estilo oversize",
    category: "buzos",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357576/buzoDrew_zffwht.jpg",
  },
  {
    id: 4,
    title: "Buzo vans",
    price: 6000,
    stock: 2,
    description: "Buzo vans sin capucha",
    category: "buzos",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357576/buzoVans_qiinf9.jpg",
  },
  {
    id: 5,
    title: "Buzo polar",
    price: 6800,
    stock: 5,
    description: "Buzo polar con capucha y bolsillo canguro",
    category: "buzos",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357574/buzoPolar_opny7z.jpg",
  },
  {
    id: 6,
    title: "Buzo Adidas",
    price: 7500,
    stock: 2,
    description: "Buzo cancugo con capucha de tres colores",
    category: "buzos",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357575/buzoAdidasColor_i29h1n.jpg",
  },
  {
    id: 7,
    title: "Pantalon Nike",
    price: 7000,
    stock: 6,
    description: "Pantalon elastizado ideal para hacer ejercicio",
    category: "pantalones",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357578/pantalonNike_lvl3t6.jpg",
  },
  {
    id: 8,
    title: "Pantalon jogger",
    price: 7500,
    stock: 4,
    description: "Pantalon canchero tendencia 2023",
    category: "pantalones",
    img: "https://res.cloudinary.com/dpmexolyn/image/upload/v1682357575/pantalonColor_e9dmrd.jpg",
  },
];
